export const Data = [
  {
    name: 'temporaryPatientsForTestingPurposeOnly P1',
    rank: 1,
    penalty: 1,
    initialOrder: 1,
  },
  {
    name: 'temporaryPatientsForTestingPurposeOnly P2',
    rank: 2,
    penalty: 1,
    initialOrder: 2,
  },
  {
    name: 'temporaryPatientsForTestingPurposeOnly P3',
    rank: 3,
    penalty: 1,
    initialOrder: 3,
  },
  {
    name: 'temporaryPatientsForTestingPurposeOnly P4',
    rank: 4,
    penalty: 1,
    initialOrder: 4,
  },
  {
    name: 'temporaryPatientsForTestingPurposeOnly P5',
    rank: 5,
    penalty: 1,
    initialOrder: 5,
  },
  {
    name: 'temporaryPatientsForTestingPurposeOnly P6',
    rank: 6,
    penalty: 1,
    initialOrder: 6,
  },
  {
    name: 'temporaryPatientsForTestingPurposeOnly P7',
    rank: 7,
    penalty: 1,
    initialOrder: 7,
  },
  {
    name: 'temporaryPatientsForTestingPurposeOnly P8',
    rank: 8,
    penalty: 1,
    initialOrder: 8,
  },
  {
    name: 'temporaryPatientsForTestingPurposeOnly P9',
    rank: 9,
    penalty: 1,
    initialOrder: 9,
  },
  {
    name: 'temporaryPatientsForTestingPurposeOnly P10',
    rank: 10,
    penalty: 1,
    initialOrder: 10,
  },
  {
    name: 'temporaryPatientsForTestingPurposeOnly P11',
    rank: 11,
    penalty: 1,
    initialOrder: 11,
  },
  {
    name: 'temporaryPatientsForTestingPurposeOnly P12',
    rank: 12,
    penalty: 1,
    initialOrder: 12,
  },
  {
    name: 'temporaryPatientsForTestingPurposeOnly P13',
    rank: 13,
    penalty: 1,
    initialOrder: 13,
  },
  {
    name: 'temporaryPatientsForTestingPurposeOnly P14',
    rank: 14,
    penalty: 1,
    initialOrder: 14,
  },
  {
    name: 'temporaryPatientsForTestingPurposeOnly P15',
    rank: 15,
    penalty: 1,
    initialOrder: 15,
  },
  {
    name: 'temporaryPatientsForTestingPurposeOnly P16',
    rank: 16,
    penalty: 1,
    initialOrder: 16,
  },
  {
    name: 'temporaryPatientsForTestingPurposeOnly P17',
    rank: 17,
    penalty: 1,
    initialOrder: 17,
  },
  {
    name: 'temporaryPatientsForTestingPurposeOnly P18',
    rank: 18,
    penalty: 1,
    initialOrder: 18,
  },
  {
    name: 'temporaryPatientsForTestingPurposeOnly P19',
    rank: 19,
    penalty: 1,
    initialOrder: 19,
  },
];

export const moreData = [
  { name: 'Dorian Chiu', rank: 1, penalty: 1 },
  { name: 'Forrest Kerry Kay', rank: 1, penalty: 1 },
  { name: 'Averie Caudill', rank: 1, penalty: 1 },
  { name: 'Janeth Kylie Butler', rank: 1, penalty: 1 },
  { name: 'Dawson Franz', rank: 1, penalty: 1 },
  { name: 'Braden Bilal Wharton', rank: 1, penalty: 1 },
  { name: 'Rigoberto Culpepper', rank: 1, penalty: 1 },
  { name: 'Claudia Blackwell', rank: 1, penalty: 1 },
  { name: 'Serena Montgomery', rank: 1, penalty: 1 },
  { name: 'Tatiyana Rosalie Feliciano', rank: 1, penalty: 1 },
  { name: 'Jensen Tafoya', rank: 1, penalty: 1 },
  { name: 'Lars Jensen Molnar', rank: 1, penalty: 1 },
  { name: 'Trinity Mchenry', rank: 1, penalty: 1 },
  { name: 'Analisa Maria Fallon', rank: 1, penalty: 1 },
  { name: 'Gideon Espinal', rank: 1, penalty: 1 },
  { name: 'Divya Neill', rank: 1, penalty: 1 },
  { name: 'Isaias Kyler Thurston', rank: 1, penalty: 1 },
  { name: 'Isaak Hawes', rank: 1, penalty: 1 },
  { name: 'Paula Lacy Hancock', rank: 1, penalty: 1 },
  { name: 'Flor Osorio', rank: 1, penalty: 1 },
  { name: 'Rylan Burkett', rank: 1, penalty: 1 },
  { name: 'Travis Gilberto Huang', rank: 1, penalty: 1 },
  { name: 'Elissa Joy Seal', rank: 1, penalty: 1 },
  { name: 'Aron Clinton Haggerty', rank: 1, penalty: 1 },
  { name: 'Aria Stefanie Nunn', rank: 1, penalty: 1 },
  { name: 'Titus Kelton Boehm', rank: 1, penalty: 1 },
  { name: 'Pablo Jon Chavis', rank: 1, penalty: 1 },
  { name: 'Makaela Crenshaw', rank: 1, penalty: 1 },
  { name: 'Olivia Hayli Wellman', rank: 1, penalty: 1 },
  { name: 'Carlee Capps', rank: 1, penalty: 1 },
  { name: 'Angelique Alyssia Gupta', rank: 1, penalty: 1 },
  { name: 'Halley Salisbury', rank: 1, penalty: 1 },
  { name: 'Enoch Dillon Christy', rank: 1, penalty: 1 },
  { name: 'Reagan Winters', rank: 1, penalty: 1 },
  { name: 'Heath Lars Edmonds', rank: 1, penalty: 1 },
  { name: 'Sasha Dutton', rank: 1, penalty: 1 },
  { name: 'Sonny Rust', rank: 1, penalty: 1 },
  { name: 'Caleb Kaufman', rank: 1, penalty: 1 },
  { name: 'Reuben Tate Tirado', rank: 1, penalty: 1 },
  { name: 'Janet Bender', rank: 1, penalty: 1 },
  { name: 'Abraham Shepherd', rank: 1, penalty: 1 },
  { name: 'Roy Perales', rank: 1, penalty: 1 },
  { name: 'Elise Moriarty', rank: 1, penalty: 1 },
  { name: 'Eryn Lexie Doucette', rank: 1, penalty: 1 },
  { name: 'Maleah Livingston', rank: 1, penalty: 1 },
  { name: 'Abbie Trinh', rank: 1, penalty: 1 },
  { name: 'Mathew Salvador', rank: 1, penalty: 1 },
  { name: 'Julianne Doll', rank: 1, penalty: 1 },
  { name: 'Vanessa Boucher', rank: 1, penalty: 1 },
  { name: 'Eva Irvin', rank: 1, penalty: 1 },
  { name: 'Ajay Howell', rank: 1, penalty: 1 },
  { name: 'Dylon Rashad Simonson', rank: 1, penalty: 1 },
  { name: 'Tayler Kade Cobb', rank: 1, penalty: 1 },
  { name: 'Kellie Gissell Burris', rank: 1, penalty: 1 },
  { name: 'Ramon Joshua Rangel', rank: 1, penalty: 1 },
  { name: 'Chelsea Jadyn Reyna', rank: 1, penalty: 1 },
  { name: 'Vincenzo Jaylin Venegas', rank: 1, penalty: 1 },
  { name: 'Nikhil Lilly', rank: 1, penalty: 1 },
  { name: 'Chloe Maryam Briones', rank: 1, penalty: 1 },
  { name: 'Raymundo Post', rank: 1, penalty: 1 },
  { name: 'Daron Alfredo Hollingsworth', rank: 1, penalty: 1 },
  { name: 'Gregory Elvin Borden', rank: 1, penalty: 1 },
  { name: 'Charlene Yolanda Souza', rank: 1, penalty: 1 },
  { name: 'Reilly Currier', rank: 1, penalty: 1 },
  { name: 'Ayla Shepard', rank: 1, penalty: 1 },
  { name: 'Macie Lusk', rank: 1, penalty: 1 },
  { name: 'Kole Snead', rank: 1, penalty: 1 },
  { name: 'Taya Heredia', rank: 1, penalty: 1 },
  { name: 'Kierra Theresa Snow', rank: 1, penalty: 1 },
  { name: 'Krystal Robin Denney', rank: 1, penalty: 1 },
  { name: 'Lisbeth Jailyn Dorman', rank: 1, penalty: 1 },
  { name: 'Demetrius Goss', rank: 1, penalty: 1 },
  { name: 'Maxine Bergman', rank: 1, penalty: 1 },
  { name: 'Baby Kamron Giles', rank: 1, penalty: 1 },
  { name: 'Dionte Hurst', rank: 1, penalty: 1 },
  { name: 'Maggie Provost', rank: 1, penalty: 1 },
  { name: 'Anastasia Liberty German', rank: 1, penalty: 1 },
  { name: 'Aman Jacquez Dalton', rank: 1, penalty: 1 },
  { name: 'Bryana Mason Gantt', rank: 1, penalty: 1 },
  { name: 'Jakobe Custer', rank: 1, penalty: 1 },
  { name: 'Caleigh Lafferty', rank: 1, penalty: 1 },
  { name: 'Samuel Goldman', rank: 1, penalty: 1 },
  { name: 'Ricky Alberto McClain', rank: 1, penalty: 1 },
  { name: 'Elian Nathen Sneed', rank: 1, penalty: 1 },
  { name: 'Samantha Edge', rank: 1, penalty: 1 },
  { name: 'Blake Petersen', rank: 1, penalty: 1 },
  { name: 'Gemma Beaver', rank: 1, penalty: 1 },
  { name: 'Blaine Yehuda Trinidad', rank: 1, penalty: 1 },
  { name: 'Marisol Isha Dehart', rank: 1, penalty: 1 },
  { name: 'Aisha Geneva Birch', rank: 1, penalty: 1 },
  { name: 'Makenna Meagan Cohen', rank: 1, penalty: 1 },
  { name: 'Izaiah Brock Fleck', rank: 1, penalty: 1 },
  { name: 'Juliet Karleigh Steen', rank: 1, penalty: 1 },
  { name: 'Lilly Willoughby', rank: 1, penalty: 1 },
  { name: 'Charlotte Nadia Lay', rank: 1, penalty: 1 },
  { name: 'Grant Fogle', rank: 1, penalty: 1 },
  { name: 'Alaina Jenna Denton', rank: 1, penalty: 1 },
  { name: 'Quincy Elliott Benton', rank: 1, penalty: 1 },
  { name: 'Blaise Lockett', rank: 1, penalty: 1 },
  { name: 'Keara Jonas', rank: 1, penalty: 1 },
];
